restaurant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("",include('waimai.urls')),
    path('admin/', admin.site.urls),
]

waimai/urls.py
from django.urls import path

from . import views
app_name = 'waimai'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

waimai/models.py
from django.db import models

# Create your models here.

waimai/views.py
from django.shortcuts import render

def home_page(request):

    if request.method == 'POST':
        dish = request.POST.get('dish')
        address = request.POST.get("address")

        return render(request, 'waimai/home_page.html', {'dish': dish, 'address': address})

    return render(request, 'waimai/home_page.html')

waimai/templates/waimai/home_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Prince Benson Waima</title>
</head>
<body>
  <h1>Prince Benson Fusion Restaurant</h1>
  <p>Tasty Treats To Your Door</p>

  <h2>Here are all the dishes!</h2>

  <!-- Dish1 -->
  <p>Big belly burger:30RMB</p>
  <img src="http://media-cdn.tripadvisor.com/media/photo-s/06/58/18/d0/big-belly-burger-deli.jpg">
  <br>

  <!-- Dish2 -->
  <p>Double cook meat:20RMB</p>
  <img src="http://img3.imgtn.bdimg.com/it/u=2080564261,814243034&fm=27&gp=0.jpg">
  <br>

  <!-- Dish3 -->
  <p>Super cool watermelon juce:28RMB</p>
  <img src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2444803618,4114539490&fm=27&gp=0.jpg">

  <!-- Order form -->
  <h2>Place your Order</h2>
	<form action="{% url 'waimai:home_page' %}" method="POST">
		{% csrf_token %}	
		<input type="text" name="dish" placeholder="Please Type Which Dish You Want"><br>
		<textarea name="address" placeholder="Please Type Your Address"></textarea><br>
		<input type="submit" value="Place Your Order">
	</form>

	<!-- Show Order -->
	<h1>Your Order:</h1>
	<p>Dish Ordered: {{dish}}</p>
	<p>Delivery Address: {{address}}</p>
</body>
</html>